events {}

http {
    #  proxy is an intermediary server that sits between your device and the broader internet
    proxy_set_header Host $host;
    # proxy_http_version 1.1: use HTTP/1.1 protocol , used for websocket connections
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    # upstream is a way to define a group of servers that can be used to proxy requests to.
    upstream frontend_app { server frontend:5173; }
    upstream auth_api     { server auth-service:8000; }
    upstream task_api     { server task-service:8000; }
    upstream gamification_api { server gamification-service:8000; }

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        # django built-in static files(CSS, JS, images, etc.)
        # used by
        # 1. The admin site
        # 2. drf-spectacular : is a third-party add-on for Django REST Framework (DRF).
        # 3. Swagger UI
        location /static/ {
            proxy_pass http://auth_api;
        }

        # django built-in admin site
        location /admin/ {
            proxy_pass http://auth_api;
        }

        # task-service
        location /api/task/ {
            proxy_pass http://task_api;
        }

        # gamification-service
        location /api/gamification/ {
            proxy_pass http://gamification_api;
        }

        # auth-service
        location /api/ {
            proxy_pass http://auth_api/api/;
        }

        # frontend
        location / {
            proxy_pass http://frontend_app;
        }
    }
}


# any variable that starts with $ is a variable that is set by the client.
# | Variable	                 | Where it comes from	                                         | Example                    |
# |------------------------------|---------------------------------------------------------------|----------------------------|
# | $host	                     | The Host header from the browser (domain you typed)	         | localhost                  |
# | $scheme	                     | How the client connected to nginx	                         | https or http              |
# | $http_upgrade	             | The Upgrade header from the browser (if present)	             | websocket (for hot reload) |
# | $proxy_add_x_forwarded_for   | Built from the client IP + any existing X-Forwarded-For chain | 192.168.1.5                |
