# Generated by Django 6.0.5 on 2026-06-04 09:57

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionEvent',
            fields=[
                ('completion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid_id', models.UUIDField(db_index=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid_id', models.UUIDField(db_index=True, unique=True)),
                ('main_level', models.PositiveIntegerField(default=0)),
                ('overall_xp', models.PositiveIntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid_id', models.UUIDField(db_index=True)),
                ('category', models.CharField(choices=[('health', 'Health'), ('learning', 'Learning'), ('responsibility', 'Responsibility'), ('creativity', 'Creativity')], max_length=255)),
                ('level', models.PositiveIntegerField(default=0)),
                ('xp_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kid_id', 'category'), name='unique_kid_category')],
            },
        ),
    ]
