# Generated by Django 6.0.8 on 2026-08-05 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completionevent',
            name='coins_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='completionevent',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completionevent',
            name='stat_level_ups',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='kidstat',
            name='xp_percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddIndex(
            model_name='completionevent',
            index=models.Index(fields=['kid_id', 'seen_at'], name='gamificatio_kid_id_f99881_idx'),
        ),
    ]
