# Generated by Django 6.0.8 on 2026-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_completionevent_coins_awarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kidstat',
            name='category',
            field=models.CharField(choices=[('health', 'Health'), ('learning', 'Learning'), ('responsibility', 'Responsibility'), ('creativity', 'Creativity'), ('honesty', 'Honesty')], max_length=255),
        ),
    ]
