# Generated by Django 5.x on 2026-07-21

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_kidcategoryvisibility_task_should_be_reviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid_id', models.UUIDField(db_index=True)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, default='')),
                ('action', models.CharField(choices=[('allowed', 'Allowed'), ('blocked', 'Blocked')], max_length=16)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
