# Generated by Django 6.0.6 on 2026-06-25 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hat', 'Hat'), ('outfit', 'Outfit'), ('accessory', 'Accessory'), ('background', 'Background')], max_length=50)),
                ('image_url', models.TextField()),
                ('coin_cost', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KidAvatar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid_id', models.UUIDField(db_index=True, unique=True)),
                ('base_character', models.CharField(default='default', max_length=50)),
                ('unlocked_items', models.JSONField(default=list)),
                ('equipped_hat', models.UUIDField(blank=True, null=True)),
                ('equipped_outfit', models.UUIDField(blank=True, null=True)),
                ('equipped_accessory', models.UUIDField(blank=True, null=True)),
                ('equipped_background', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kid_id', models.UUIDField(db_index=True)),
                ('coins_spent', models.PositiveIntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.avataritem')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
