# Generated by Django 6.0.7 on 2026-07-24 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_id', models.UUIDField(db_index=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='parent_avatars/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
