# Generated by Django 6.0.7 on 2026-07-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_parentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidavatar',
            name='equipped_character',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avataritem',
            name='type',
            field=models.CharField(choices=[('character', 'Character'), ('hat', 'Hat'), ('outfit', 'Outfit'), ('accessory', 'Accessory'), ('background', 'Background')], max_length=50),
        ),
    ]
