# Generated by Django 6.0.7 on 2026-07-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_kidavatar_equipped_character_alter_avataritem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidavatar',
            old_name='equipped_character',
            new_name='equipped_hair',
        ),
        migrations.RemoveField(
            model_name='kidavatar',
            name='equipped_hat',
        ),
        migrations.RemoveField(
            model_name='kidavatar',
            name='equipped_outfit',
        ),
        migrations.AlterField(
            model_name='avataritem',
            name='type',
            field=models.CharField(choices=[('hair', 'Hair'), ('accessory', 'Accessory'), ('background', 'Background')], max_length=50),
        ),
    ]
