# Generated by Django 6.0.7 on 2026-07-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_equipped_character_kidavatar_equipped_hair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avataritem',
            name='param_key',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='avataritem',
            name='param_value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
