# Generated by Django 6.0.7 on 2026-07-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_avataritem_param_key_avataritem_param_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kidavatar',
            old_name='equipped_accessory',
            new_name='equipped_earrings',
        ),
        migrations.AddField(
            model_name='kidavatar',
            name='equipped_glasses',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avataritem',
            name='type',
            field=models.CharField(choices=[('hair', 'Hair'), ('glasses', 'Glasses'), ('earrings', 'Earrings'), ('background', 'Background')], max_length=50),
        ),
    ]
