# Generated by Django 6.0.7 on 2026-07-18 11:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_kid_id', models.UUIDField(db_index=True)),
                ('to_kid_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('from_kid_id', models.F('to_kid_id')), _negated=True), name='social_friendship_no_self'), models.UniqueConstraint(fields=('from_kid_id', 'to_kid_id'), name='uniq_friendship_direction')],
            },
        ),
    ]
