# Generated by Django 6.0.6 on 2026-06-22 05:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_id', models.UUIDField(db_index=True)),
                ('notification_type', models.CharField(choices=[('task_confirmed', 'Task Confirmed'), ('task_rejected', 'Task Rejected'), ('task_submitted', 'Task Submitted'), ('level_up', 'Level Up')], max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
