# Generated by Django 6.0.8 on 2026-08-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_confirmed', 'Task Confirmed'), ('task_rejected', 'Task Rejected'), ('task_submitted', 'Task Submitted'), ('level_up', 'Level Up'), ('friend_request', 'Friend Request')], max_length=50),
        ),
    ]
