# Generated by Django 6.0.5 on 2026-05-10 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def set_active_registration_for_linked_kids(apps, schema_editor):
    Kid = apps.get_model("users", "Kid")
    Kid.objects.exclude(parent_id__isnull=True).update(registration_status="active")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='registration_status',
            field=models.CharField(choices=[('awaiting_primary_parent', 'Awaiting primary parent'), ('active', 'Active'), ('suspended', 'Suspended')], db_index=True, default='awaiting_primary_parent', max_length=32),
        ),
        migrations.AlterField(
            model_name='kid',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GuardianInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invite_email', models.EmailField(max_length=254)),
                ('invited_username_hint', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_by_kid', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_invitations', to='users.kid')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('kid', 'invite_email'), name='uniq_pending_guardian_invite_email_per_kid')],
            },
        ),
        migrations.RunPython(set_active_registration_for_linked_kids, migrations.RunPython.noop),
    ]
