# Generated by Django 6.0.8 on 2026-08-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_bio_kid_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='kid',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
