# Generated by Django 6.0.8 on 2026-08-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_username_alter_kid_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='password_reset_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kid',
            name='password_reset_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
